#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../configs/llama_final.env"
cd "$DERMAGENT_REPO_ROOT"

export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-$LLAMA_FINAL_GPU_MEMORY_UTILIZATION}"
export MAX_MODEL_LEN="${MAX_MODEL_LEN:-$LLAMA_FINAL_MAX_MODEL_LEN}"
export MAX_NUM_SEQS="${MAX_NUM_SEQS:-$LLAMA_FINAL_MAX_NUM_SEQS}"
export SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-$LLAMA_SERVER_MODEL}"
export OPENAI_API_KEY="${OPENAI_API_KEY:-$LLAMA_SERVER_API_KEY}"

exec bash "${DERMAGENT_REPO_ROOT}/scripts/start_llama_server.sh" "$DERMAGENT_REPO_ROOT"
