#!/usr/bin/env bash
set -euo pipefail

source /root/DermAgent/final-script/configs/dermatollama_final.env
cd "$DERMAGENT_REPO_ROOT"

export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-$DERMATOLLAMA_FINAL_GPU_MEMORY_UTILIZATION}"
export MAX_MODEL_LEN="${MAX_MODEL_LEN:-$DERMATOLLAMA_FINAL_MAX_MODEL_LEN}"
export MAX_NUM_SEQS="${MAX_NUM_SEQS:-$DERMATOLLAMA_FINAL_MAX_NUM_SEQS}"
export LORA_MODULE_NAME="${LORA_MODULE_NAME:-$DERMATOLLAMA_SERVER_MODEL}"
export OPENAI_API_KEY="${OPENAI_API_KEY:-$DERMATOLLAMA_SERVER_API_KEY}"

exec bash /root/DermAgent/scripts/start_dermatollama_server.sh "$DERMAGENT_REPO_ROOT"
