from __future__ import annotations


SCIN_FULL_LABELS = (
    "AKV - Acrokeratosis verruciformis",
    "Abrasion and/or friction burn of lower limb without infection",
    "Abrasion and/or friction burn of thigh without infection",
    "Abrasion of wrist",
    "Abrasion, scrape, or scab",
    "Abscess",
    "Acanthosis nigricans",
    "Acne",
    "Acne keloidalis",
    "Acne urticata",
    "Acneiform eruption",
    "Acquired digital fibrokeratoma",
    "Acquired poikiloderma",
    "Acral erythema",
    "Acral persistent papular mucinosis",
    "Actinic Keratosis",
    "Actinic granuloma",
    "Acute and chronic dermatitis",
    "Acute constitutional eczema",
    "Acute dermatitis",
    "Acute dermatitis, NOS",
    "Acute generalised exanthematous pustulosis",
    "Acute ulcer of skin",
    "Acute vesicular dermatitis",
    "Acute-on-chronic dyshidrotic eczema of hands",
    "Adnexal neoplasm",
    "Agminate folliculitis",
    "Allergic Contact Dermatitis",
    "Allergic contact dermatitis caused by allergenic hapten derived from plant",
    "Amyloidosis of skin",
    "Anetoderma",
    "Angiokeratoma of skin",
    "Angiosarcoma of skin",
    "Animal bite - wound",
    "Annular erythema",
    "Arsenical keratosis",
    "Atrophic glossitis",
    "Atypical Nevus",
    "Autoimmune diseases affecting skin",
    "B-Cell Cutaneous Lymphoma",
    "Bacterial pyoderma",
    "Basal Cell Carcinoma",
    "Benign cutaneous vascular tumor",
    "Benign tumor of dermis",
    "Berloque dermatitis",
    "Blister",
    "Blood blister",
    "Bullosis diabeticorum",
    "Bullous Pemphigoid",
    "Bullous dermatitis",
    "Bullous dermatitis, NOS",
    "Bullous dermatosis",
    "Burn erythema of abdominal wall",
    "Burn erythema of back of hand",
    "Burn erythema of lower leg",
    "Burn erythema of neck",
    "Burn of forearm",
    "Burn of skin",
    "CD - Contact dermatitis",
    "Calcinosis cutis",
    "Calciphylaxis cutis",
    "Candida",
    "Candida infection of flexural skin",
    "Candida intertrigo",
    "Candidal intertrigo",
    "Cat scratch disease",
    "Cat scratch injury",
    "Cellulitis",
    "Cellulitis of hand excluding finger",
    "Cheilitis",
    "Chemical leukoderma",
    "Chicken pox exanthem",
    "Chilblain",
    "Chronic dermatitis",
    "Chronic dermatitis, NOS",
    "Chronic ulcer of skin",
    "Clavus",
    "Clinical neurofibromatosis",
    "Collagenoma",
    "Comedone",
    "Condyloma acuminatum",
    "Confluent and reticulate papillomatosis",
    "Contact burn of skin",
    "Contact dermatitis caused by Rhus diversiloba",
    "Contact dermatitis, NOS",
    "Contact purpura",
    "Crohn disease of skin",
    "Crusted eczematous dermatitis",
    "Cutaneous T Cell Lymphoma",
    "Cutaneous larva migrans",
    "Cutaneous leishmaniasis",
    "Cutaneous lupus",
    "Cutaneous lyme disease",
    "Cutaneous metastasis",
    "Cutaneous polyarteritis nodosa",
    "Cutaneous sarcoidosis",
    "Cyst",
    "Darier's disease",
    "Deep fungal infection",
    "Dehiscence",
    "Dermatitis herpetiformis",
    "Dermatofibroma",
    "Dermatofibrosarcoma protuberans",
    "Dermatomyositis",
    "Dermatosis caused by lice",
    "Dermatosis due to flea",
    "Diffuse xanthoma",
    "Discrete papular lichen myxedematosus",
    "Drug Rash",
    "Drug induced abnormal pigmentation of skin",
    "Drug-induced pellagra",
    "Drug-induced photosensitivity",
    "Ecthyma",
    "Ecthyma gangrenosum",
    "Eczema",
    "Elephantiasis nostras",
    "Epidermal nevus",
    "Erosion of skin",
    "Eruptive odontogenic cyst",
    "Eruptive xanthoma",
    "Erysipelas",
    "Erythema ab igne",
    "Erythema annulare centrifugum",
    "Erythema dyschromicum perstans",
    "Erythema elevatum diutinum",
    "Erythema gyratum repens",
    "Erythema marginatum",
    "Erythema marginatum in acute rheumatic fever",
    "Erythema migrans",
    "Erythema multiforme",
    "Erythema nodosum",
    "Flagellate erythema",
    "Flushing",
    "Folliculitis",
    "Folliculitis decalvans",
    "Foot ulcer",
    "Foreign body",
    "Foreign body reaction of the skin",
    "Fox-Fordyce disease",
    "Frontal fibrosing alopecia",
    "Fungal dermatitis",
    "Fungal dermatosis",
    "Furuncle",
    "Geographic tongue",
    "Granuloma annulare",
    "Granuloma faciale",
    "Granulomatous disorder of the skin and subcutaneous tissue",
    "Grover's disease",
    "HK - Hyperkeratosis",
    "Hailey Hailey disease",
    "Hand foot and mouth disease",
    "Hemangioma",
    "Hematoma of skin",
    "Hemosiderin pigmentation of lower limb due to varicose veins of lower limb",
    "Hemosiderin pigmentation of skin",
    "Hemosiderin pigmentation of skin due to venous insufficiency",
    "Herpes Simplex",
    "Herpes Zoster",
    "Hidradenitis",
    "Histiocytosis of skin",
    "Hyperkeratosis of skin",
    "Hyperpigmentation",
    "Hyperpigmentation disorder",
    "Hypersensitivity",
    "Ichthyosiform dermatosis",
    "Ichthyosis",
    "Idiopathic guttate hypomelanosis",
    "Impetigo",
    "Infected eczema",
    "Infection of skin",
    "Infection of tick bite",
    "Infection of toe web",
    "Infestation caused by Sarcoptes scabiei var bovis",
    "Inflammatory dermatosis",
    "Inflicted skin lesions",
    "Ingrown hair",
    "Injection site disorder",
    "Insect Bite",
    "Intertrigo",
    "Inverse psoriasis",
    "Irritant Contact Dermatitis",
    "Itchy skin eruption",
    "Jessner lymphocytic infiltrate",
    "Kaposi's sarcoma of skin",
    "Keratoderma",
    "Keratolysis exfoliativa",
    "Keratosis",
    "Keratosis pilaris",
    "Knuckle pads",
    "Koebner phenomenon",
    "Lentigo",
    "Leprosy",
    "Leukemia cutis",
    "Leukocytoclastic Vasculitis",
    "Leukonychia",
    "Lichen Simplex Chronicus",
    "Lichen nitidus",
    "Lichen planus/lichenoid eruption",
    "Lichen sclerosus",
    "Lichen spinulosus",
    "Lichen striatus",
    "Lichenified eczema",
    "Lichenified eczematous dermatitis",
    "Lichenoid myxedema",
    "Linear IgA disease",
    "Lipoma",
    "Livedo reticularis",
    "Livedoid vasculopathy",
    "Local infection of wound",
    "Localised cutaneous vasculitis",
    "Localised skin eruption due to drugs and medicaments",
    "Localised skin infection",
    "Localized cutaneous vasculitis",
    "Localized skin infection",
    "Lymphangioma",
    "Lymphocutaneous sporotrichosis",
    "Lymphomatoid papulosis",
    "Majocchi granuloma",
    "Majocchi's granuloma",
    "Mastocytoma",
    "Melanin pigmentation due to exogenous substance",
    "Melanocytic Nevus",
    "Melanoma",
    "Melasma",
    "Milia",
    "Miliaria",
    "Mixed diabetic ulcer - foot",
    "Molluscum Contagiosum",
    "Morbilliform eruption",
    "Morphea/Scleroderma",
    "Muehrcke lines",
    "Mycetoma",
    "Nail dystrophy",
    "Nail dystrophy due to trauma",
    "Nail pitting",
    "Necrobiosis lipoidica",
    "Neoplasm of uncertain behavior of skin of arm",
    "Nevus anemicus",
    "Nodular vasculitis",
    "Non-melanin pigmentation due to exogenous substance (disorder)",
    "Non-specific panniculitis",
    "O/E - ecchymoses present",
    "O/E - petechiae on skin",
    "O/E - petechiae present",
    "O/E - purulent pustules",
    "O/E - pustules",
    "O/E - skin cyst present",
    "O/E - skin fissure",
    "O/E - vesicles present",
    "OK - Odontogenic keratocyst",
    "Ochronosis",
    "On examination - follicular pustules",
    "On examination - hemorrhagic bullae",
    "Onychodystrophy",
    "Onychomycosis",
    "PXE (pseudoxanthoma elasticum) like syndrome",
    "Pachyonychia congenita",
    "Paget disease",
    "Panniculitis",
    "Panniculitis, NOS",
    "Papular acrodermatitis of childhood",
    "Parapsoriasis",
    "Paronychia",
    "Pemphigoid gestationis",
    "Pemphigus",
    "Pemphigus foliaceus",
    "Pemphigus vulgaris",
    "Perforating dermatosis",
    "Perifollicular haemorrhage",
    "Perifolliculitis",
    "Perioral Dermatitis",
    "Perleche",
    "Petechiae",
    "Photocontact dermatitis [berloque dermatitis]",
    "Photodermatitis",
    "Phytophotodermatitis",
    "Pigmented purpuric eruption",
    "Pincer nail deformity",
    "Pityriasis alba",
    "Pityriasis lichenoides",
    "Pityriasis rosea",
    "Pityriasis rubra pilaris",
    "Poikiloderma",
    "Poisoning by nematocyst",
    "Porokeratosis",
    "Post-Inflammatory hyperpigmentation",
    "Post-Inflammatory hypopigmentation",
    "Pressure ulcer",
    "Pressure ulcer stage 2",
    "Pretibial myxedema",
    "Primary cutaneous lymphoma",
    "Prurigo",
    "Prurigo nodularis",
    "Pruritic dermatitis",
    "Pruritic urticarial papules and plaques of pregnancy",
    "Pseudolymphoma",
    "Psoriasiform dermatitis",
    "Psoriasis",
    "Purpura",
    "Pyoderma",
    "Pyoderma Gangrenosum",
    "Pyogenic granuloma",
    "RMSF - Rocky Mountain spotted fever",
    "Remove from labeling tool",
    "Rheumatoid nodule",
    "Rosacea",
    "Rosai Dorfman disease - I know rare, but I've seen a case like this unilateral. Rosacea supported bilateral further images",
    "SCC/SCCIS",
    "SK/ISK",
    "SLE - Systemic lupus erythematosus-related syndrome",
    "Scabies",
    "Scar Condition",
    "Seborrheic Dermatitis",
    "Secondary impetiginization",
    "Skin and soft tissue atypical mycobacterial infection",
    "Skin atrophy",
    "Skin cancer",
    "Skin hypopigmented",
    "Skin infection",
    "Skin lesion in drug addict",
    "Skin striae",
    "Skin ulcer",
    "Small plaque parapsoriasis",
    "Snake bite - wound",
    "Sneddon-Wilkinson disease",
    "Stasis Dermatitis",
    "Sunburn",
    "Superficial frostbite",
    "Superficial wound of body region",
    "Sweet syndrome",
    "Syphilis",
    "TMEP - telangiectasia macularis eruptiva perstans",
    "Tinea",
    "Tinea Versicolor",
    "Traction alopecia",
    "Traumatic blister",
    "Traumatic petechiae",
    "Traumatic ulcer",
    "Tuberculosis of skin and subcutaneous tissue",
    "Tufted angioma of skin",
    "Urticaria",
    "Urticarial vasculitis",
    "Varicose veins of lower extremity",
    "Vascular nevus of skin",
    "Vasculitis of the skin",
    "Vasculitis of the skin, NOS",
    "Venous Stasis Ulcer",
    "Verruca vulgaris",
    "Viral Exanthem",
    "Viral dermatological disorders",
    "Viral infection of skin",
    "Vitiligo",
    "Xanthoma",
    "Xerosis",
    "deep fungal infection",
    "deep vein thrombosis",
    "digital myxoid cyst",
    "gouty tophi",
    "granular parakeratosis",
    "hyperlinear palm",
    "panniculitis of skin",
    "pathergy",
    "post-sunburn peeling/superficial desquamation",
    "relapsing polychondritis",
    "resolving dermatitis",
    "scurvy",
    "superficial hemorrhage",
    "unilateral laterothoracic exanthem",
    "varicose vein",
    "wound/abrasion",
)

SCIN_MALIGNANT_LABELS = (
    "Actinic Keratosis",
    "B-Cell Cutaneous Lymphoma",
    "Basal Cell Carcinoma",
    "Cutaneous T Cell Lymphoma",
    "Cutaneous metastasis",
    "Dermatofibrosarcoma protuberans",
    "Kaposi's sarcoma of skin",
    "Leukemia cutis",
    "Melanoma",
    "Paget disease",
    "Primary cutaneous lymphoma",
    "SCC/SCCIS",
    "Skin cancer",
)

SCIN_GROUPED_CANONICAL_LABELS = (
    "DERMATITIS_ECZEMA",
    "URTICARIA_BITE_FOLLICULITIS",
    "INFECTION_VIRAL_FUNGAL",
    "VASCULAR_PURPURIC",
    "ACNE_ROSACEA_FOLLICULAR",
    "PIGMENT_KERATOSIS_NEVUS",
    "MALIGNANT_PREMALIGNANT",
    "OTHER",
)
