from __future__ import annotations


SD198_RAW_LABELS = (
    "Acne_Keloidalis_Nuchae",
    "Acne_Vulgaris",
    "Acrokeratosis_Verruciformis",
    "Actinic_solar_Damage(Actinic_Cheilitis)",
    "Actinic_solar_Damage(Actinic_Keratosis)",
    "Actinic_solar_Damage(Cutis_Rhomboidalis_Nuchae)",
    "Actinic_solar_Damage(Pigmentation)",
    "Actinic_solar_Damage(Solar_Elastosis)",
    "Actinic_solar_Damage(Solar_Purpura)",
    "Actinic_solar_Damage(Telangiectasia)",
    "Acute_Eczema",
    "Allergic_Contact_Dermatitis",
    "Alopecia_Areata",
    "Androgenetic_Alopecia",
    "Angioma",
    "Angular_Cheilitis",
    "Aphthous_Ulcer",
    "Apocrine_Hydrocystoma",
    "Arsenical_Keratosis",
    "Balanitis_Xerotica_Obliterans",
    "Basal_Cell_Carcinoma",
    "Beau's_Lines",
    "Becker's_Nevus",
    "Behcet's_Syndrome",
    "Benign_Keratosis",
    "Blue_Nevus",
    "Bowen's_Disease",
    "Bowenoid_Papulosis",
    "Cafe_Au_Lait_Macule",
    "Callus",
    "Candidiasis",
    "Cellulitis",
    "Chalazion",
    "Clubbing_of_Fingers",
    "Compound_Nevus",
    "Congenital_Nevus",
    "Crowe's_Sign",
    "Cutanea_Larva_Migrans",
    "Cutaneous_Horn",
    "Cutaneous_T-Cell_Lymphoma",
    "Cutis_Marmorata",
    "Darier-White_Disease",
    "Dermatofibroma",
    "Dermatosis_Papulosa_Nigra",
    "Desquamation",
    "Digital_Fibroma",
    "Dilated_Pore_of_Winer",
    "Discoid_Lupus_Erythematosus",
    "Disseminated_Actinic_Porokeratosis",
    "Drug_Eruption",
    "Dry_Skin_Eczema",
    "Dyshidrosiform_Eczema",
    "Dysplastic_Nevus",
    "Eccrine_Poroma",
    "Eczema",
    "Epidermal_Nevus",
    "Epidermoid_Cyst",
    "Epithelioma_Adenoides_Cysticum",
    "Erythema_Ab_Igne",
    "Erythema_Annulare_Centrifigum",
    "Erythema_Craquele",
    "Erythema_Multiforme",
    "Exfoliative_Erythroderma",
    "Factitial_Dermatitis",
    "Favre_Racouchot",
    "Fibroma",
    "Fibroma_Molle",
    "Fixed_Drug_Eruption",
    "Follicular_Mucinosis",
    "Follicular_Retention_Cyst",
    "Fordyce_Spots",
    "Frictional_Lichenoid_Dermatitis",
    "Ganglion",
    "Geographic_Tongue",
    "Granulation_Tissue",
    "Granuloma_Annulare",
    "Green_Nail",
    "Guttate_Psoriasis",
    "Hailey_Hailey_Disease",
    "Half_and_Half_Nail",
    "Halo_Nevus",
    "Herpes_Simplex_Virus",
    "Herpes_Zoster",
    "Hidradenitis_Suppurativa",
    "Histiocytosis_X",
    "Hyperkeratosis_Palmaris_Et_Plantaris",
    "Hypertrichosis",
    "Ichthyosis",
    "Impetigo",
    "Infantile_Atopic_Dermatitis",
    "Inverse_Psoriasis",
    "Junction_Nevus",
    "Keloid",
    "Keratoacanthoma",
    "Keratolysis_Exfoliativa_of_Wende",
    "Keratosis_Pilaris",
    "Kerion",
    "Koilonychia",
    "Kyrle's_Disease",
    "Leiomyoma",
    "Lentigo_Maligna_Melanoma",
    "Leukocytoclastic_Vasculitis",
    "Leukonychia",
    "Lichen_Planus",
    "Lichen_Sclerosis_Et_Atrophicus",
    "Lichen_Simplex_Chronicus",
    "Lichen_Spinulosis",
    "Linear_Epidermal_Nevus",
    "Lipoma",
    "Livedo_Reticularis",
    "Lymphangioma_Circumscriptum",
    "Lymphocytic_Infiltrate_of_Jessner",
    "Lymphomatoid_Papulosis",
    "Mal_Perforans",
    "Malignant_Melanoma",
    "Median_Nail_Dystrophy",
    "Melasma",
    "Metastatic_Carcinoma",
    "Milia",
    "Molluscum_Contagiosum",
    "Morphea",
    "Mucha_Habermann_Disease",
    "Mucous_Membrane_Psoriasis",
    "Myxoid_Cyst",
    "Nail_Dystrophy",
    "Nail_Nevus",
    "Nail_Psoriasis",
    "Nail_Ridging",
    "Neurodermatitis",
    "Neurofibroma",
    "Neurotic_Excoriations",
    "Nevus_Comedonicus",
    "Nevus_Incipiens",
    "Nevus_Sebaceous_of_Jadassohn",
    "Nevus_Spilus",
    "Nummular_Eczema",
    "Onychogryphosis",
    "Onycholysis",
    "Onychomycosis",
    "Onychoschizia",
    "Paronychia",
    "Pearl_Penile_Papules",
    "Perioral_Dermatitis",
    "Pincer_Nail_Syndrome",
    "Pitted_Keratolysis",
    "Pityriasis_Alba",
    "Pityriasis_Rosea",
    "Pityrosporum_Folliculitis",
    "Poikiloderma_Atrophicans_Vasculare",
    "Pomade_Acne",
    "Pseudofolliculitis_Barbae",
    "Pseudorhinophyma",
    "Psoriasis",
    "Pustular_Psoriasis",
    "Pyoderma_Gangrenosum",
    "Pyogenic_Granuloma",
    "Racquet_Nail",
    "Radiodermatitis",
    "Rhinophyma",
    "Rosacea",
    "Scalp_Psoriasis",
    "Scar",
    "Scarring_Alopecia",
    "Schamberg's_Disease",
    "Sebaceous_Gland_Hyperplasia",
    "Seborrheic_Dermatitis",
    "Seborrheic_Keratosis",
    "Skin_Tag",
    "Solar_Lentigo",
    "Stasis_Dermatitis",
    "Stasis_Edema",
    "Stasis_Ulcer",
    "Steroid_Acne",
    "Steroid_Striae",
    "Steroid_Use_abusemisuse_Dermatitis",
    "Stomatitis",
    "Strawberry_Hemangioma",
    "Striae",
    "Subungual_Hematoma",
    "Syringoma",
    "Terry's_Nails",
    "Tinea_Corporis",
    "Tinea_Cruris",
    "Tinea_Faciale",
    "Tinea_Manus",
    "Tinea_Pedis",
    "Tinea_Versicolor",
    "Toe_Deformity",
    "Trichilemmal_Cyst",
    "Trichofolliculoma",
    "Trichostasis_Spinulosa",
    "Ulcer",
    "Urticaria",
    "Varicella",
    "Verruca_Vulgaris",
    "Vitiligo",
    "Wound_Infection",
    "Xerosis",
)

SD198_MALIGNANT_OR_PREMALIGNANT_RAW_LABELS = frozenset(
    {
        "Actinic_solar_Damage(Actinic_Cheilitis)",
        "Actinic_solar_Damage(Actinic_Keratosis)",
        "Arsenical_Keratosis",
        "Basal_Cell_Carcinoma",
        "Bowen's_Disease",
        "Bowenoid_Papulosis",
        "Cutaneous_T-Cell_Lymphoma",
        "Disseminated_Actinic_Porokeratosis",
        "Keratoacanthoma",
        "Lentigo_Maligna_Melanoma",
        "Lymphomatoid_Papulosis",
        "Malignant_Melanoma",
        "Metastatic_Carcinoma",
    }
)


def humanize_sd198_label(raw_label: str) -> str:
    text = str(raw_label).strip().replace("_", " ")
    text = text.replace("(", " (").replace(")", ")")
    return " ".join(text.split())


SD198_RAW_TO_CANONICAL = {
    raw_label: humanize_sd198_label(raw_label)
    for raw_label in SD198_RAW_LABELS
}

SD198_FULL_LABELS = tuple(SD198_RAW_TO_CANONICAL[raw_label] for raw_label in SD198_RAW_LABELS)

SD198_MALIGNANT_LABELS = frozenset(
    SD198_RAW_TO_CANONICAL[raw_label]
    for raw_label in SD198_MALIGNANT_OR_PREMALIGNANT_RAW_LABELS
)

SD198_GROUPED_CANONICAL_LABELS = (
    "SUN_DAMAGE_ACTINIC",
    "MALIGNANT_SKIN_CANCER",
    "PIGMENTARY_NEVUS_KERATOSIS",
    "BENIGN_TUMOR_CYST",
    "DERMATITIS_ECZEMA",
    "PAPULOSQUAMOUS_KERATOTIC",
    "ACNE_FOLLICULITIS_ROSACEA",
    "INFECTION_INFESTATION",
    "HAIR_NAIL_APPENDAGE",
    "VASCULAR_ULCER_PURPURA",
    "MUCOSAL_GENITAL_ORAL",
    "OTHER",
)

SD198_GROUPED_MALIGNANT_LABELS = frozenset({"MALIGNANT_SKIN_CANCER"})

_SD198_GROUPED_EXACT_MAP = {
    "Acne Keloidalis Nuchae": "ACNE_FOLLICULITIS_ROSACEA",
    "Acne Vulgaris": "ACNE_FOLLICULITIS_ROSACEA",
    "Acrokeratosis Verruciformis": "PAPULOSQUAMOUS_KERATOTIC",
    "Actinic solar Damage (Actinic Cheilitis)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Actinic Keratosis)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Cutis Rhomboidalis Nuchae)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Pigmentation)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Solar Elastosis)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Solar Purpura)": "SUN_DAMAGE_ACTINIC",
    "Actinic solar Damage (Telangiectasia)": "SUN_DAMAGE_ACTINIC",
    "Acute Eczema": "DERMATITIS_ECZEMA",
    "Allergic Contact Dermatitis": "DERMATITIS_ECZEMA",
    "Alopecia Areata": "HAIR_NAIL_APPENDAGE",
    "Androgenetic Alopecia": "HAIR_NAIL_APPENDAGE",
    "Angioma": "VASCULAR_ULCER_PURPURA",
    "Angular Cheilitis": "MUCOSAL_GENITAL_ORAL",
    "Aphthous Ulcer": "MUCOSAL_GENITAL_ORAL",
    "Apocrine Hydrocystoma": "BENIGN_TUMOR_CYST",
    "Arsenical Keratosis": "SUN_DAMAGE_ACTINIC",
    "Balanitis Xerotica Obliterans": "MUCOSAL_GENITAL_ORAL",
    "Basal Cell Carcinoma": "MALIGNANT_SKIN_CANCER",
    "Beau's Lines": "HAIR_NAIL_APPENDAGE",
    "Becker's Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Behcet's Syndrome": "MUCOSAL_GENITAL_ORAL",
    "Benign Keratosis": "PIGMENTARY_NEVUS_KERATOSIS",
    "Blue Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Bowen's Disease": "MALIGNANT_SKIN_CANCER",
    "Bowenoid Papulosis": "MALIGNANT_SKIN_CANCER",
    "Cafe Au Lait Macule": "PIGMENTARY_NEVUS_KERATOSIS",
    "Callus": "PAPULOSQUAMOUS_KERATOTIC",
    "Candidiasis": "INFECTION_INFESTATION",
    "Cellulitis": "INFECTION_INFESTATION",
    "Chalazion": "BENIGN_TUMOR_CYST",
    "Clubbing of Fingers": "HAIR_NAIL_APPENDAGE",
    "Compound Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Congenital Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Crowe's Sign": "PIGMENTARY_NEVUS_KERATOSIS",
    "Cutanea Larva Migrans": "INFECTION_INFESTATION",
    "Cutaneous Horn": "SUN_DAMAGE_ACTINIC",
    "Cutaneous T-Cell Lymphoma": "MALIGNANT_SKIN_CANCER",
    "Cutis Marmorata": "VASCULAR_ULCER_PURPURA",
    "Darier-White Disease": "PAPULOSQUAMOUS_KERATOTIC",
    "Dermatofibroma": "BENIGN_TUMOR_CYST",
    "Dermatosis Papulosa Nigra": "PIGMENTARY_NEVUS_KERATOSIS",
    "Desquamation": "DERMATITIS_ECZEMA",
    "Digital Fibroma": "BENIGN_TUMOR_CYST",
    "Dilated Pore of Winer": "BENIGN_TUMOR_CYST",
    "Discoid Lupus Erythematosus": "DERMATITIS_ECZEMA",
    "Disseminated Actinic Porokeratosis": "SUN_DAMAGE_ACTINIC",
    "Drug Eruption": "DERMATITIS_ECZEMA",
    "Dry Skin Eczema": "DERMATITIS_ECZEMA",
    "Dyshidrosiform Eczema": "DERMATITIS_ECZEMA",
    "Dysplastic Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Eccrine Poroma": "BENIGN_TUMOR_CYST",
    "Eczema": "DERMATITIS_ECZEMA",
    "Epidermal Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Epidermoid Cyst": "BENIGN_TUMOR_CYST",
    "Epithelioma Adenoides Cysticum": "BENIGN_TUMOR_CYST",
    "Erythema Ab Igne": "SUN_DAMAGE_ACTINIC",
    "Erythema Annulare Centrifigum": "DERMATITIS_ECZEMA",
    "Erythema Craquele": "DERMATITIS_ECZEMA",
    "Erythema Multiforme": "DERMATITIS_ECZEMA",
    "Exfoliative Erythroderma": "DERMATITIS_ECZEMA",
    "Factitial Dermatitis": "DERMATITIS_ECZEMA",
    "Favre Racouchot": "SUN_DAMAGE_ACTINIC",
    "Fibroma": "BENIGN_TUMOR_CYST",
    "Fibroma Molle": "BENIGN_TUMOR_CYST",
    "Fixed Drug Eruption": "DERMATITIS_ECZEMA",
    "Follicular Mucinosis": "ACNE_FOLLICULITIS_ROSACEA",
    "Follicular Retention Cyst": "BENIGN_TUMOR_CYST",
    "Fordyce Spots": "MUCOSAL_GENITAL_ORAL",
    "Frictional Lichenoid Dermatitis": "DERMATITIS_ECZEMA",
    "Ganglion": "BENIGN_TUMOR_CYST",
    "Geographic Tongue": "MUCOSAL_GENITAL_ORAL",
    "Granulation Tissue": "VASCULAR_ULCER_PURPURA",
    "Granuloma Annulare": "DERMATITIS_ECZEMA",
    "Green Nail": "INFECTION_INFESTATION",
    "Guttate Psoriasis": "PAPULOSQUAMOUS_KERATOTIC",
    "Hailey Hailey Disease": "PAPULOSQUAMOUS_KERATOTIC",
    "Half and Half Nail": "HAIR_NAIL_APPENDAGE",
    "Halo Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Herpes Simplex Virus": "INFECTION_INFESTATION",
    "Herpes Zoster": "INFECTION_INFESTATION",
    "Hidradenitis Suppurativa": "ACNE_FOLLICULITIS_ROSACEA",
    "Histiocytosis X": "OTHER",
    "Hyperkeratosis Palmaris Et Plantaris": "PAPULOSQUAMOUS_KERATOTIC",
    "Hypertrichosis": "HAIR_NAIL_APPENDAGE",
    "Ichthyosis": "PAPULOSQUAMOUS_KERATOTIC",
    "Impetigo": "INFECTION_INFESTATION",
    "Infantile Atopic Dermatitis": "DERMATITIS_ECZEMA",
    "Inverse Psoriasis": "PAPULOSQUAMOUS_KERATOTIC",
    "Junction Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Keloid": "BENIGN_TUMOR_CYST",
    "Keratoacanthoma": "MALIGNANT_SKIN_CANCER",
    "Keratolysis Exfoliativa of Wende": "PAPULOSQUAMOUS_KERATOTIC",
    "Keratosis Pilaris": "ACNE_FOLLICULITIS_ROSACEA",
    "Kerion": "INFECTION_INFESTATION",
    "Koilonychia": "HAIR_NAIL_APPENDAGE",
    "Kyrle's Disease": "PAPULOSQUAMOUS_KERATOTIC",
    "Leiomyoma": "BENIGN_TUMOR_CYST",
    "Lentigo Maligna Melanoma": "MALIGNANT_SKIN_CANCER",
    "Leukocytoclastic Vasculitis": "VASCULAR_ULCER_PURPURA",
    "Leukonychia": "HAIR_NAIL_APPENDAGE",
    "Lichen Planus": "PAPULOSQUAMOUS_KERATOTIC",
    "Lichen Sclerosis Et Atrophicus": "MUCOSAL_GENITAL_ORAL",
    "Lichen Simplex Chronicus": "DERMATITIS_ECZEMA",
    "Lichen Spinulosis": "PAPULOSQUAMOUS_KERATOTIC",
    "Linear Epidermal Nevus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Lipoma": "BENIGN_TUMOR_CYST",
    "Livedo Reticularis": "VASCULAR_ULCER_PURPURA",
    "Lymphangioma Circumscriptum": "VASCULAR_ULCER_PURPURA",
    "Lymphocytic Infiltrate of Jessner": "DERMATITIS_ECZEMA",
    "Lymphomatoid Papulosis": "MALIGNANT_SKIN_CANCER",
    "Mal Perforans": "VASCULAR_ULCER_PURPURA",
    "Malignant Melanoma": "MALIGNANT_SKIN_CANCER",
    "Median Nail Dystrophy": "HAIR_NAIL_APPENDAGE",
    "Melasma": "PIGMENTARY_NEVUS_KERATOSIS",
    "Metastatic Carcinoma": "MALIGNANT_SKIN_CANCER",
    "Milia": "BENIGN_TUMOR_CYST",
    "Molluscum Contagiosum": "INFECTION_INFESTATION",
    "Morphea": "DERMATITIS_ECZEMA",
    "Mucha Habermann Disease": "PAPULOSQUAMOUS_KERATOTIC",
    "Mucous Membrane Psoriasis": "MUCOSAL_GENITAL_ORAL",
    "Myxoid Cyst": "BENIGN_TUMOR_CYST",
    "Nail Dystrophy": "HAIR_NAIL_APPENDAGE",
    "Nail Nevus": "HAIR_NAIL_APPENDAGE",
    "Nail Psoriasis": "HAIR_NAIL_APPENDAGE",
    "Nail Ridging": "HAIR_NAIL_APPENDAGE",
    "Neurodermatitis": "DERMATITIS_ECZEMA",
    "Neurofibroma": "BENIGN_TUMOR_CYST",
    "Neurotic Excoriations": "DERMATITIS_ECZEMA",
    "Nevus Comedonicus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Nevus Incipiens": "PIGMENTARY_NEVUS_KERATOSIS",
    "Nevus Sebaceous of Jadassohn": "PIGMENTARY_NEVUS_KERATOSIS",
    "Nevus Spilus": "PIGMENTARY_NEVUS_KERATOSIS",
    "Nummular Eczema": "DERMATITIS_ECZEMA",
    "Onychogryphosis": "HAIR_NAIL_APPENDAGE",
    "Onycholysis": "HAIR_NAIL_APPENDAGE",
    "Onychomycosis": "INFECTION_INFESTATION",
    "Onychoschizia": "HAIR_NAIL_APPENDAGE",
    "Paronychia": "INFECTION_INFESTATION",
    "Pearl Penile Papules": "MUCOSAL_GENITAL_ORAL",
    "Perioral Dermatitis": "ACNE_FOLLICULITIS_ROSACEA",
    "Pincer Nail Syndrome": "HAIR_NAIL_APPENDAGE",
    "Pitted Keratolysis": "INFECTION_INFESTATION",
    "Pityriasis Alba": "DERMATITIS_ECZEMA",
    "Pityriasis Rosea": "PAPULOSQUAMOUS_KERATOTIC",
    "Pityrosporum Folliculitis": "ACNE_FOLLICULITIS_ROSACEA",
    "Poikiloderma Atrophicans Vasculare": "VASCULAR_ULCER_PURPURA",
    "Pomade Acne": "ACNE_FOLLICULITIS_ROSACEA",
    "Pseudofolliculitis Barbae": "ACNE_FOLLICULITIS_ROSACEA",
    "Pseudorhinophyma": "ACNE_FOLLICULITIS_ROSACEA",
    "Psoriasis": "PAPULOSQUAMOUS_KERATOTIC",
    "Pustular Psoriasis": "PAPULOSQUAMOUS_KERATOTIC",
    "Pyoderma Gangrenosum": "VASCULAR_ULCER_PURPURA",
    "Pyogenic Granuloma": "VASCULAR_ULCER_PURPURA",
    "Racquet Nail": "HAIR_NAIL_APPENDAGE",
    "Radiodermatitis": "SUN_DAMAGE_ACTINIC",
    "Rhinophyma": "ACNE_FOLLICULITIS_ROSACEA",
    "Rosacea": "ACNE_FOLLICULITIS_ROSACEA",
    "Scalp Psoriasis": "PAPULOSQUAMOUS_KERATOTIC",
    "Scar": "OTHER",
    "Scarring Alopecia": "HAIR_NAIL_APPENDAGE",
    "Schamberg's Disease": "VASCULAR_ULCER_PURPURA",
    "Sebaceous Gland Hyperplasia": "BENIGN_TUMOR_CYST",
    "Seborrheic Dermatitis": "DERMATITIS_ECZEMA",
    "Seborrheic Keratosis": "PIGMENTARY_NEVUS_KERATOSIS",
    "Skin Tag": "BENIGN_TUMOR_CYST",
    "Solar Lentigo": "SUN_DAMAGE_ACTINIC",
    "Stasis Dermatitis": "VASCULAR_ULCER_PURPURA",
    "Stasis Edema": "VASCULAR_ULCER_PURPURA",
    "Stasis Ulcer": "VASCULAR_ULCER_PURPURA",
    "Steroid Acne": "ACNE_FOLLICULITIS_ROSACEA",
    "Steroid Striae": "OTHER",
    "Steroid Use abusemisuse Dermatitis": "DERMATITIS_ECZEMA",
    "Stomatitis": "MUCOSAL_GENITAL_ORAL",
    "Strawberry Hemangioma": "VASCULAR_ULCER_PURPURA",
    "Striae": "OTHER",
    "Subungual Hematoma": "HAIR_NAIL_APPENDAGE",
    "Syringoma": "BENIGN_TUMOR_CYST",
    "Terry's Nails": "HAIR_NAIL_APPENDAGE",
    "Tinea Corporis": "INFECTION_INFESTATION",
    "Tinea Cruris": "INFECTION_INFESTATION",
    "Tinea Faciale": "INFECTION_INFESTATION",
    "Tinea Manus": "INFECTION_INFESTATION",
    "Tinea Pedis": "INFECTION_INFESTATION",
    "Tinea Versicolor": "INFECTION_INFESTATION",
    "Toe Deformity": "HAIR_NAIL_APPENDAGE",
    "Trichilemmal Cyst": "BENIGN_TUMOR_CYST",
    "Trichofolliculoma": "BENIGN_TUMOR_CYST",
    "Trichostasis Spinulosa": "ACNE_FOLLICULITIS_ROSACEA",
    "Ulcer": "VASCULAR_ULCER_PURPURA",
    "Urticaria": "DERMATITIS_ECZEMA",
    "Varicella": "INFECTION_INFESTATION",
    "Verruca Vulgaris": "INFECTION_INFESTATION",
    "Vitiligo": "PIGMENTARY_NEVUS_KERATOSIS",
    "Wound Infection": "INFECTION_INFESTATION",
    "Xerosis": "DERMATITIS_ECZEMA",
}

SD198_FULL_TO_GROUPED = {
    humanize_sd198_label(raw_label): _SD198_GROUPED_EXACT_MAP[humanize_sd198_label(raw_label)]
    for raw_label in SD198_RAW_LABELS
}

SD198_GROUPED_KEYWORDS = {
    "SUN_DAMAGE_ACTINIC": (
        "sun damage",
        "actinic",
        "solar elastosis",
        "solar purpura",
        "radiodermatitis",
        "favre racouchot",
        "photodamage",
    ),
    "MALIGNANT_SKIN_CANCER": (
        "skin cancer",
        "carcinoma",
        "melanoma",
        "lymphoma",
        "bowen",
        "bowenoid",
        "keratoacanthoma",
        "metastatic",
    ),
    "PIGMENTARY_NEVUS_KERATOSIS": (
        "nevus",
        "lentigo",
        "melasma",
        "vitiligo",
        "pigment",
        "cafe au lait",
        "seborrheic keratosis",
        "benign keratosis",
    ),
    "BENIGN_TUMOR_CYST": (
        "cyst",
        "fibroma",
        "lipoma",
        "ganglion",
        "poroma",
        "hydrocystoma",
        "syringoma",
        "sebaceous gland hyperplasia",
        "skin tag",
        "milia",
        "chalazion",
    ),
    "DERMATITIS_ECZEMA": (
        "eczema",
        "dermatitis",
        "urticaria",
        "drug eruption",
        "erythema",
        "erythroderma",
        "xerosis",
        "morphea",
        "granuloma annulare",
    ),
    "PAPULOSQUAMOUS_KERATOTIC": (
        "psoriasis",
        "lichen planus",
        "ichthyosis",
        "hyperkeratosis",
        "darier",
        "hailey",
        "kyrle",
        "callus",
        "pityriasis rosea",
        "papulosquamous",
    ),
    "ACNE_FOLLICULITIS_ROSACEA": (
        "acne",
        "folliculitis",
        "rosacea",
        "hidradenitis",
        "rhinophyma",
        "pseudofolliculitis",
        "keratosis pilaris",
    ),
    "INFECTION_INFESTATION": (
        "infection",
        "infect",
        "tinea",
        "herpes",
        "impetigo",
        "candidiasis",
        "cellulitis",
        "molluscum",
        "varicella",
        "verruca",
        "larva migrans",
        "onychomycosis",
        "paronychia",
        "kerion",
    ),
    "HAIR_NAIL_APPENDAGE": (
        "alopecia",
        "nail",
        "onych",
        "beau",
        "koilonychia",
        "leukonychia",
        "subungual",
        "clubbing",
        "hypertrichosis",
        "toe deformity",
    ),
    "VASCULAR_ULCER_PURPURA": (
        "angioma",
        "hemangioma",
        "vasculitis",
        "vascular",
        "purpura",
        "livedo",
        "stasis",
        "ulcer",
        "pyogenic granuloma",
        "pyoderma gangrenosum",
        "lymphangioma",
    ),
    "MUCOSAL_GENITAL_ORAL": (
        "cheilitis",
        "aphthous",
        "balanitis",
        "geographic tongue",
        "stomatitis",
        "penile",
        "fordyce",
        "behcet",
        "mucous membrane",
    ),
    "OTHER": (
        "scar",
        "striae",
        "histiocytosis",
        "other",
    ),
}


def sd198_grouped_label_for_text(text: str) -> str:
    normalized = " ".join(str(text).strip().lower().split())
    if not normalized:
        return "OTHER"

    exact = _SD198_GROUPED_EXACT_MAP.get(" ".join(str(text).strip().split()))
    if exact:
        return exact

    for grouped_label, keywords in SD198_GROUPED_KEYWORDS.items():
        if any(keyword in normalized for keyword in keywords):
            return grouped_label
    return "OTHER"
